### ISSUE TITLE
Creating separators in prefabs doesn't seem to work

### ISSUE THREAD

**Issue by Michoko92** [truongnguyentungduy/hierarchy-2#11]
Hi,

I'd like to create separators in my prefabs (as they can get pretty complex), but it doesn't work with Hierarchy 2. Whenever I try, nothing happens, and the separator is instead created in the main hierachy. Is there a way to make it work please?

Thank you!

**Comment by truongnguyentungduy** [comment]
It's by design.
https://github.com/truongnguyentungduy/hierarchy-2/blob/27774bfc54ef3800bbfc91b3a0826b97c20c717f/Assets/Hierarchy%202/Editor/HierarchyEditor.cs#L558
But, you can try to remove the "rowItem.isRootObject" condition. it might also require a little tweaking somewhere.
