### ISSUE TITLE
Bug - Settings not save

### ISSUE THREAD

**Issue by tracer8** [truongnguyentungduy/hierarchy-2#12]
Hi,
When changing setting. It is not save to Settings.asset file.
When i close then reopen Unity. Settings reset to default.

**Comment by bblessed** [comment]
Can confirm is also happening to me.

**Comment by tracer8** [comment]
I need to modify manual by hand on Settings.asset file to make it save.

**Comment by truongnguyentungduy** [comment]
d0c99de

**Comment by truongnguyentungduy** [comment]
d0c99de

**Comment by truongnguyentungduy** [comment]
d0c99de

**Comment by truongnguyentungduy** [comment]
d0c99de
